name: Daily Commit Workflow

on:
  schedule:
    - cron: '17 10 * * *' # Runs daily at 10:17 UTC (adjust if needed)

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add update for 24f1002326@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily update"
          git push
